set nocompatible
set t_Co=256

" -----------------------
" config for NeoVundle
" -----------------------
filetype off

if has('vim_starting')
  set runtimepath+=~/.vim/bundle/neobundle.vim
  call neobundle#rc(expand('~/.vim/bundle/'))
endif

" for code completion
NeoBundle 'Shougo/neocomplete.vim'
"NeoBundle has('lua') ? 'Shougo/neocomplete' : 'Shougo/neocomplcache'

" for faster execution
NeoBundle 'quickrun.vim'

" for git
NeoBundle 'tpope/vim-fugitive'

" for svn
NeoBundle 'vcscommand.vim'

" easier to comment
NeoBundle 'scrooloose/nerdcommenter'

" for syntax check
NeoBundle 'scrooloose/syntastic'

" ファイラみたいな
NeoBundle "Shougo/unite.vim"

NeoBundle 'Shougo/vimproc'

" L9 has need for FuzzyFinder
NeoBundle 'L9'
NeoBundle 'FuzzyFinder'

" for python complition
NeoBundle 'davidhalter/jedi-vim'

" -----------------------
" neocomplete
" -----------------------
let g:neocomplete#enable_at_startup = 1

" quickrun の実行とかぶるので変更
let g:jedi#rename_command = "<leader>R"

" neocomplete と jedi をうまいこと共存させるための設定
" http://kozo2.hatenablog.com/entry/2014/01/22/050714
autocmd FileType python setlocal omnifunc=jedi#completions
" 補完の最初の項目が選択された状態だと使いにくいためオフにする
"let g:jedi#popup_select_first=0
let g:jedi#completions_enabled = 0
let g:jedi#auto_vim_configuration = 0

colorscheme ron

" insert modeで開始
let g:unite_enable_start_insert = 1

" 大文字小文字を区別しない
let g:unite_enable_ignore_case = 1
let g:unite_enable_smart_case = 1

" grep検索
nnoremap <silent> ,g  :<C-u>Unite grep:. -buffer-name=search-buffer -default-action=tabopen<CR>

" カーソル位置の単語をgrep検索
nnoremap <silent> ,cg :<C-u>Unite grep:. -buffer-name=search-buffer -default-action=tabopen<CR><C-R><C-W>

" unite grep で候補を選択した時にタブで開くようにする
"call unite#custom_default_action('grep', 'tabopen')

let g:unite_source_history_yank_enable =1
let g:unite_source_file_mru_limit = 200
"let g:unite_source_file_rec_min_cache_files = 10
nnoremap <silent> ,y :<C-u>Unite history/yank<CR>
nnoremap <silent> ,b :<C-u>Unite buffer<CR>
nnoremap <silent> ,f :<C-u>UniteWithBufferDir -buffer-name=files file<CR>
nnoremap <silent> ,r :<C-u>Unite -buffer-name=register register<CR>
nnoremap <silent> ,u :<C-u>Unite file_mru buffer<CR>
nnoremap <silent> ,e  :<C-u>Unite file_rec/async:<CR>
nnoremap <silent> ,p :<C-u>call <SID>unite_project('-start-insert')<CR>

let g:unite_source_rec_unit = 20000
let g:unite_source_rec_async_command = 'ack -f --nofilter'
"if exists("unite#custom#source")
"  call unite#custom#source('file_rec/async', 'ignore_pattern', '\(\.idea.*\|zip\|swf\|png\|gif\|jpeg\|jpg\|\.git.*\)$')
"endif
if exists("unite#custom#source")
call unite#custom#source('file_rec/async', 'ignore_pattern', '\(png\|gif\|jpeg\|jpg\)$') 
endif
let g:unite_source_rec_max_cache_files = 20000
"let g:unite_data_directory='~/cachecacheunite'

let g:unite_source_rec_min_cache_files = 10
function! s:unite_project(...)
  let opts = (a:0 ? join(a:000, ' ') : '')
  let dir = unite#util#path2project_directory(expand('%'))
  execute 'Unite' opts 'file_rec/async:' . dir
endfunction

" unite grep に ag(The Silver Searcher) を使う
if executable('pt')
  let g:unite_source_grep_command = 'pt'
  let g:unite_source_grep_default_opts = '--nogroup --nocolor '
  let g:unite_source_grep_recursive_opt = ''
endif

let g:ctrlp_cache_dir = $HOME.'/.cache/ctrlp'

let g:quickrun_config = {
    \   "_" : {
    \       "runner" : "vimproc",
    \       "runner/vimproc/updatetime" : 40,
    \       "running_mark": ">>>",
    \       "hook/time/enable": 1,
    \       "outputter/quickfix": "&errorformat",
    \}
\}
let g:quickrun_config["python"] = {
    \ 'exec' : ['python3 %s', '']
\}

filetype plugin indent on

" 特殊文字があると表示がずれる問題の対策
" のはずが、有効にすると悲惨なことに
"set ambiwidth=double
set ambiwidth=single

" -----------------------
" nerdcommenter
" -----------------------
" コメントした後に挿入するスペース数
let NERDSpaceDelims = 1
nmap ,, <Plug>NERDCommenterToggle
vmap ,, <Plug>NERDCommenterToggle

" -----------------------
" FuzzyFinder.vim
" -----------------------
" need for FufMruFile
let g:fuf_modesDisable = []

nnoremap <Space>f f
nnoremap <Space>F F
nnoremap f <Nop>

nnoremap <silent> fc :<C-u>FufRenewCache!<CR>
nnoremap <silent> fb :<C-u>FufBuffer!<CR>
nnoremap <silent> ff :<C-u>FufFile!<C-r>=expand('%:~:.')[:-1-len(expand('%:~:.:t'))]<CR><CR>
nnoremap <silent> fm :<C-u>FufMruFile!<CR>
nnoremap <silent> tb :<C-u>tabnew<CR>:tabmove<CR>:FufBuffer!<CR>
nnoremap <silent> tf :<C-u>tabnew<CR>:tabmove<CR>:FufFile!<C-r>=expand('#:~:.')[:-1-len(expand('#:~:.:t'))]<CR><CR>
nnoremap <silent> tm :<C-u>tabnew<CR>:tabmove<CR>:FufMruFile!<CR>

syntax on
filetype plugin on
filetype indent on


set viminfo='50,\"14000,:0,n~/.viminfo

set encoding=utf-8
set termencoding=utf-8
set fileencoding=utf-8
set fileencodings=utf-8,euc-jp,sjis,iso-2022-jp,cp932
set fileformats=unix,dos,mac

set backspace=indent,eol,start
set formatoptions+=m
set list
set listchars=tab:>-,extends:<,trail:-
set hidden

set wildmenu
set showmatch

set wrapscan
set ignorecase
set smartcase
set incsearch
set hlsearch

set autoindent
set smartindent
set expandtab
set smarttab

"スワップファイルの出力先を ~/.vim/tmp/swap に変更
set directory=~/tmp/vim/swap

"set tabstop=4
"set softtabstop=4
"set shiftwidth=4

set laststatus=2
set statusline=[%n]\ %t\ %y%{GetStatusEx()}\ %m%h%r=%l/%L,%c%V\ %P

" 環境によってデフォルトの色設定が異なるので明示的に指定する
highlight Normal ctermbg=black ctermfg=white
highlight StatusLine term=none cterm=none ctermfg=black ctermbg=grey
highlight CursorLine term=none cterm=none ctermfg=none ctermbg=darkgray
highlight Pmenu ctermbg=darkblue

highlight ZenkakuSpace cterm=underline ctermfg=lightblue
match ZenkakuSpace /　/

"inoremap <C-t> <C-v><Tab>
"inoremap <C-j> <Down>
"inoremap <C-k> <Up>
"inoremap <C-h> <Left>
"inoremap <C-l> <Right>

"nnoremap <C-l> <ESC>:ls<CR>
"nnoremap <C-p> <ESC>:bp<CR>
"nnoremap <C-n> <ESC>:bn<CR>

" ノーマルモードのまま空行を入れる
" キーバインドが重なっているのでコメントアウト
"nnoremap <C-o> :<C-u>call append(expand('.'), '')<Cr>

noremap j gj
noremap k gk
noremap gj j
noremap gk k

nnoremap ,.  :<C-u>edit $MYVIMRC<Enter>
nnoremap ,s. :<C-u>source $MYVIMRC<Enter>

nnoremap gc `[V`]
vnoremap gc :<C-u>normal gc<Enter>
onoremap gc :<C-u>normal gc<Enter>

autocmd FileType php setlocal tabstop=4 softtabstop=4 shiftwidth=4 expandtab
autocmd FileType html setlocal tabstop=2 softtabstop=2 shiftwidth=2 noexpandtab
autocmd FileType ruby setlocal tabstop=2 softtabstop=2 shiftwidth=2 expandtab
autocmd FileType smarty setlocal tabstop=2 softtabstop=2 shiftwidth=2 noexpandtab
autocmd BufNewFile,BufRead *.twig set syntax=htmldjango

au BufNewFile,BufRead *.cgi  set ft=perl
au BufNewFile,BufRead *.psgi set ft=perl

function! GetStatusEx()
    let str = &fileformat
    if has("multi_byte") && &fileencoding != ""
        let str = &fileencoding . ":" . str
    endif
    let str = "[" . str . "]"
    return str
endfunction

"バイナリ編集(xxd)モード（vim -b での起動、もしくは *.bin ファイルを開くと発動します）
augroup BinaryXXD
  autocmd!
  autocmd BufReadPre  *.bin let &binary =1
  autocmd BufReadPost * if &binary | silent %!xxd -g 1
  autocmd BufReadPost * set ft=xxd | endif
  autocmd BufWritePre * if &binary | %!xxd -r | endif
  autocmd BufWritePost * if &binary | silent %!xxd -g 1
  autocmd BufWritePost * set nomod | endif
augroup END


